### ISSUE TITLE
Panic when doing read_line often enough - failure to cross block boundaries?

### ISSUE THREAD

**Issue by curoli** [informationsea/bgzip-rs#3]
I'm getting panics such as these, both for versions 0.1.0 and 0.2.0:

```
thread 'main' panicked at 'internal error: entered unreachable code', /home/oliverr/.cargo/registry/src/github.com-1ecc6299db9ec823/bgzip-0.2.0/src/read.rs:130:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:50:5
   3: <bgzip::read::BGZFReader<R> as std::io::BufRead>::fill_buf
             at /home/oliverr/.cargo/registry/src/github.com-1ecc6299db9ec823/bgzip-0.2.0/src/read.rs:130:9
   4: std::io::read_until
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/io/mod.rs:1766:35
   5: std::io::BufRead::read_line::{{closure}}
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/io/mod.rs:2025:35
   6: std::io::append_to_string
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/io/mod.rs:333:19
   7: std::io::BufRead::read_line
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/io/mod.rs:2025:9
   8: selene::join::join_input_with_data
             at ./src/join.rs:93:52
   9: selene::run
             at ./src/lib.rs:41:5
  10: selene::main
             at ./src/main.rs:2:11
  11: core::ops::function::FnOnce::call_once
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:227:5
```

Just checking: this is supposed to be able to read across block boundaries, right? Thanks!

**Comment by shahamran** [comment]
I encountered the same problemm I don't think it's a cross-blocks issue.
After playing with it a bit, I found a minimal example:
```bash
$ printf "hello\n\n" | bgzip > tmp.gz
```
Now reading `tmp.gz` in a `read_line()` loop reaches the "unreachable" code in `fill_buf()`.
It seems the reader assumes it needs to read more than 0 bytes before reaching a newline. I'm not sure how to work around it though, I don't understand the code well enough.

The code that crashed is:
```rust
use std::{fs::File, io::BufRead};
use bgzip::BGZFReader;

fn main() {
    let filename = "/path/to/tmp.gz";
    let mut br = BGZFReader::new(File::open(filename).unwrap());
    let mut buf = String::new();
    loop {
        buf.clear();
        match br.read_line(&mut buf) {
            Ok(0) => { break; }
            Ok(_) => { continue; }
            Err(_) => { break; }
        }
    }
}
```
